### ISSUE TITLE
Fork question

### ISSUE THREAD

**Issue by dgeo** [fractalcells/ansible-iocell#3]
Just to let you know that I forked and modified your module to get check_mode working, returning facts, working with current iocage from ports…

see https://github.com/criecm/ansible-iocage

Just to ask if you prefer me to PR all of this or to maintain my fork ?

In any case, thank you for sharing this !

**Comment by Infiniverse** [comment]
Hey dgeo, I want to report an issue against your fork, but it doesn't appear that issues are enabled. Are you interested in any feedback?

**Comment by dch** [comment]
I'm pretty sure @xmj would love a PR. Can you be specific - are your changes for the new python-flavoured iocage?

**Comment by dgeo** [comment]
@Infiniverse Of course I am :) I just activated issues on the fork…

@dch , @xmj I already opened a PR for a minor bugfix, but after no feedback I decided to work apart to make it suit my needs…

I think my fork is already almost compatible with new python iocage (but not fully tested with it now), there are some design changes (no basejail by default, workaround for properties on creation should not be needed anymore, …).

Not sure if my work is sufficiently tested (for now it just "works for me®").

If this repo is still active I'd be happy to contribute back :)

**Comment by Infiniverse** [comment]
Hey hey! Good news. I'll submit a couple of issues now.

**Comment by dgeo** [comment]
Well, it seems that there is iocell and py-iocage now, my 'fork' will follow py-iocage while this one has been renamed ansible-iocell. This seems typical opensource headache ;)
I'll continue to work on py-iocage and let this one follow iocell, future will let us know what where the better option :)
Thank you all and lets make all of these work :)

**Comment by Infiniverse** [comment]
Hey @dgeo, I think that we're going to go back to iocell for now - maybe py-iocage will mature up in time, but it's taking a long time and they've broken many things, without really adding anything worth the pain. Until they have snapshots running reliably, and dump/restore it's not production ready anyway.

Do you know if @fractalcells is still maintaining this repo?

**Comment by xmj** [comment]
Hey @Infiniverse, as Github makes a mess of notifications please reach out via email if you have any questions.

I will probably actively start doing things to @fractalcells and `ansible-iocell` come January.
